filetype on
filetype plugin on


set term=xterm-256color
syntax on
colorscheme darkblue

set number
set hlsearch

set encoding=utf-8

set list
set listchars=tab:>>-,trail:-,eol:$,extends:>,precedes:<,nbsp:%
set tabstop=4

autocmd BufRead,BufNewFile *.rc setfiletype rust

call plug#begin('~/.vim/plugged')
  Plug 'rust-lang/rust.vim'
  Plug 'neoclide/coc.nvim', {'branch': 'release'}
call plug#end()

syntax enable
filetype plugin indent on

" 保存時に自動でrustfmt
let g:rustfmt_autosave = 1
let g:coc_disable_startup_warning = 1

" Make <CR> auto-select the first completion item and notify coc.nvim to
" format on enter, <cr> could be remapped by other vim plugin
inoremap <silent><expr> <cr> pumvisible() ? coc#_select_confirm()
                              \: "\<C-g>u\<CR>\<c-r>=coc#on_enter()\<CR>"

" GoTo code navigation.
nmap <silent> gd <Plug>(coc-definition)
nmap <silent> gy <Plug>(coc-type-definition)
nmap <silent> gi <Plug>(coc-implementation)
nmap <silent> gr <Plug>(coc-references)

